import React, {useState} from 'react';
import './BillCard.css';
import axios from "axios";

function BillCard({bill}) {
    const [loading, setLoading] = useState(false);
    const [expanded, setExpanded] = useState(false);
    const [billDetails, setBillDetails] = useState(null);
    const [billSummary, setBillSummary] = useState(null);

    const toggleExpand = async () => {
        if(!expanded && !billDetails) {
            setLoading(true);
            try {
                const response = await axios.get(
                    `http://localhost:8080/api/legiscan/bill/${bill.bill_id}`
                );
                setBillDetails(response.data);
                console.log("Bill response: ");
                console.log(response.data);
            } catch(err) {
                console.log("Error fetching Bill details: " + err);
            }
            setLoading(false);
        }
        setExpanded(!expanded);
    };

    const generateSummary = async () => {
        try {
            setLoading(true);
            const response = await axios.get(
                `http://localhost:8080/api/legiscan/bill/${bill.bill_id}/summary`
            );
            setBillSummary(response.data);
            console.log("Bill AI summary: ");
            console.log(response.data);
        } catch(err) {
            console.log("Error calling AI Summary client: " + err);
        }
        setLoading(false);
    }

    return (
        <div className="bill-card">
            <div className="bill-info-card" key={bill.bill_id} onClick={toggleExpand}>
                <h1 className="bill-title">{bill.title}</h1>
                <p className="bill-number">Bill Number: {bill.bill_number}</p>
                <p className="state">State: {bill.state}</p>
                {/*<p className="last-action">Last Action:<br/> {bill.last_action}<br/> on:<br/> {bill.last_action_date}</p>*/}
                <a className="read-more" href={bill.url} target="_blank" rel="noopener noreferrer">LEGISCAN LINK</a>
            </div>

            {expanded && (
                <div className="bill-details">
                    {loading ? (
                        <p>Loading details...</p>
                    ) : billDetails ? (
                        <div>
                            <h3>Description</h3>
                            <p>{billDetails.description}</p>
                            <h3>History</h3>
                            <p><b>LATEST:</b></p>
                            {/*using spread details... to reverse as to not alter the original array.*/}
                            {billDetails.history.length > 0 ? ([...billDetails.history].reverse().map(history => (
                                <div>
                                    <p>{history.date}</p>
                                    <p>{history.action}</p>
                                </div>
                            ))) : null}

                            <a className="ai-summary" onClick={generateSummary} rel="noopener noreferrer">AI Summary</a>
                            {loading && <p>Generating summary with Claude AI...</p>}

                            {billSummary && (
                                <div className="ai-summary">
                                    <p style={{whiteSpace: 'pre-wrap'}}>{billSummary.summary}</p>
                                    <small className="summary-note">
                                        Generated by Claude AI • Cached for future requests
                                    </small>
                                </div>
                            )}
                        </div>
                    ) : null}
                </div>
            )}
        </div>
    )
}

export default BillCard;